[[pinned]]
name = "How Computers Use Numbers"
description = 'My <a href="https://some.3b1b.co">SoME3</a> submission: an interactive article about various number formats'
url = "/numbers/"
technologies = ["lit"]
icon = "/numbers/assets/icon.png"
links = { github = "https://github.com/Mabi19/numbers/" }

[[pinned]]
name = "Stardew Perfection Randomizer"
description = "A Stardew Valley challenge about achieving Perfection one step at a time"
url = "/stardew-perfection-randomizer/"
icon = "/stardew-perfection-randomizer/icon.png"
technologies = ["vue", "nuxt"]
links = { github = "https://github.com/Mabi19/stardew-perfection-randomizer/" }

[[pinned]]
name = "This website"
description = "First time using a static site generator. Still a work in progress 🚧"
icon = "/assets/icon.png"
technologies = ["lume"]
links = { github = "https://github.com/Mabi19/mabi19.github.io/" }

[[skyblock]]
name = "Luckalyzer"
description = "A luck calculator for Hypixel SkyBlock"
url = "/luckalyzer/"
icon = "/luckalyzer/icon-8x.png"
technologies = ["vue", "wasm", "rust"]
links = { github = "https://github.com/Mabi19/luckalyzer/" }

[[skyblock]]
name = "Spider's Den Forecast"
description = "A weather forecast for the Spider's Den island in Hypixel SkyBlock"
url = "/sb-forecast/"
icon = "/sb-forecast/favicon-default.png"
technologies = ["vanilla-ts"]
links = { github = "https://github.com/Mabi19/sb-forecast/" }

[[youtube]]
name = "Password Game TAS"
url = "https://www.youtube.com/watch?v=UF0xKMagtpE"
links = { github = "https://github.com/Mabi19/password-game-tas/" }

[[youtube]]
name = "bad_apple.otf"
description = "An OpenType font that plays Bad Apple!! with ligatures"
url = "https://www.youtube.com/watch?v=Oub__07I4X8"
links = { github = "https://github.com/Mabi19/bad-apple-font" }

[[misc]]
name = "Colourblind Simulator"
description = "A web app I made for a biology project. Polish-only"
url = "/colourblind-simulator/"
technologies = ["vue"]
links = { github = "https://github.com/Mabi19/colourblind-simulator/" }

[[misc]]
name = "boostedminecarts"
description = "PaperMC plugin that buffs minecart speeds"
technologies = ["java"]
links = { github = "https://github.com/Mabi19/boostedminecarts/" }
