vue = { name = "Vue" }
nuxt = { name = "Nuxt" }
lit = { name = "Lit", themed = true }
lume = { name = "Lume" }
vanilla-ts = { name = "Vanilla (TypeScript)" }
java = { name = "Java" }
wasm = { name = "WebAssembly" }
rust = { name = "Rust", themed = true }
